### ISSUE TITLE
Enumerating the Windows and DNS information of this domain Always Fails

### ISSUE THREAD

**Issue by Manuuuux** [mitre/adversary#12]
Good morning, everyone! I have a problem when it comes to performing an operation, the step of Enumerating the Windows and DNS information of this domain always fails, I do not understand very well why, I leave you the information that shows the server Caldera, any extra information you need to help me do not hesitate to ask me, Thank you very much in advance!

Dirección IP del nodo: [10.80.80.8] Id. de ámbito : []

                Tabla de nombres locales NetBIOS

       Nombre             Tipo         Estado
    ---------------------------------------------
    DESKTOP-4T1EI1R<00>  Único       Registrado 
    CORP           <00>  Grupo       Registrado 
    DESKTOP-4T1EI1R<20>  Único       Registrado 
'
INFO:app.operation.operation:Returned from get_domain
INFO:app.operation.operation:Entering planner
DEBUG:app.logic.planner:After pruning, 3 actions left to evaluate
WARNING:app.logic.planner:Planning run took 0.004591523000000208 seconds and returned 5 actions
WARNING:app.logic.planner:Dedupping took 1.0918999999942613e-05 seconds and returned 3 actions
WARNING:app.logic.planner:Optimization pruning took 1.6191000000054245e-05 seconds and returned 0 actions
WARNING:app.logic.planner:Recursion took 0.02156115500000011 seconds and explored 3 actions
WARNING:app.logic.planner:Action Breakdown:
WARNING:app.logic.planner:    2: GetAdmin
WARNING:app.logic.planner:    1: GetDomain
WARNING:app.logic.planner:    0: WMIRemoteProcessCreate
DEBUG:app.logic.planner:Processed 3 plans
INFO:app.operation.operation:Planning time took: 0.02691512499999993 seconds
INFO:app.operation.operation:Running step get_domain
WARNING:app.operation.operation:Failed to parse with error: 'Result is not well formed:

**Comment by lisicn** [comment]
@Manuuuux Thank you very much for your reply, and I am very happy to receive your invitation to publish. After consulting your suggestions, and sorting out the built-in steps of Caldera, I found that I have a lot of doubts about the network configuration. Of course, thank you very much for your reply.

**Comment by Manuuuux** [comment]
@qq854051086 attending the error, I would say that one of the problems of your laboratory is the language, you should convert the languages of your systems to English

**Comment by ArtificialErmine** [comment]
Caldera's adversary mode has only been fully tested within an English based environment. If language-based problems persist after upgrading to the most recent version of Caldera, feel free to create a new issue detailing a specific case, and we can look into it. Until then, this issue is being closed due to inactivity.
