### ISSUE TITLE
Crater RAT clarifications

### ISSUE THREAD

**Issue by amacready** [mitre/adversary#16]
Ive successfully installed Cadera on Ubuntu, created a network and installed the agent on various clients.  All looks good, I can even see thru the debug that I can communicate to the relevant client agents by sending commands and getting appropriate responses. 

However when I launch an operation nothing happens, it sits in Bootstrap mode.
Im not sure if I have this right in respect to the CraterMainWin8up RAT. Does it get pushed out to a Windows 10 client via a Caldera operation if I leave the Bootstrap RAT option selected or do I need to copy and run the CraterMainWin8up.exe on the WIndows client to ensure the RAT is available to Caldera server?

Would appreciate your help as I believe I am 95% of the way there but need understanding the built in RAT feature.

**Comment by unkempthenry** [comment]
'Send Command' will send  a command that is executed directly by cagent (the caldera agent service). 

It's useful for checking connectivity between the agent and caldera server.  You can also use it manually clean things up in case a step in cleanup fails or other light admin tasks. e.g. you can 
` taskkill /im commander.exe /f ` from this windows to kill any processes named commander.exe (the default name of the RAT). 

We should probably rename it to have a more obvious name or add a help tooltip that explains what it does.

**Comment by ArtificialErmine** [comment]
It looks like the root of this issue is an incompatibility of Chinese characters with that version of Caldera. If the problem persists after upgrading to the newest version of the Caldera project and adversary mode, feel free to re-open the issue or create a new one, and we can diagnose the issue further.
