### ISSUE TITLE
Limit line length

### ISSUE THREAD

**Issue by wisedier** [mitre/adversary#20]
Most of scripts in this project has too many "line too long" warnings.

[PEP-8](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) tells 

> limit all lines to a maximum of 79 characters. but it's okay to increase the line length limit up to 99 characters, provided that comments and docstrings are still wrapped at 72 characters.

How about to try to limit all lines to a maximum of 79 or 99 characters?

**Comment by wisedier** [comment]
It was about adver

**Comment by khyberspache** [comment]
As we push updates to the repo we are trying to adhere to PEP-8, but we aren't planning a ticket to go through the entire repo and make it PEP-8 compliant.

**Comment by wisedier** [comment]
@khyberspache Then may I try? I had already updated the code following some PEPs while analyzing the original CALDERA repository.

**Comment by khyberspache** [comment]
Go for it! Submit a PR and we will review & merge.

**Comment by ArtificialErmine** [comment]
@wisedier If you have any questions regarding the adversary plugin or making it fully PEP-8 compliant, feel free to re-open this issue. Otherwise, it would appear that the original issue has been as resolved as much as it can given the current situation and direction for the project.
