### ISSUE TITLE
Adversary Charlie Crashes Server

### ISSUE THREAD

**Issue by workandresearchgithub** [mitre/adversary#3]
When running built in Adversary Charlie, the server crashes after get_local_profiles.  Here is the server output:
--
[AdversaryCharlieServerOutput.txt](https://github.com/mitre/caldera/files/3011330/AdversaryCharlieServerOutput.txt)
--

Operational Details window:

--
![image](https://user-images.githubusercontent.com/38447728/55048152-2eba3000-5015-11e9-8030-db5f56449c5d.png)
--

Enumerating user profiles on win10client - full text capture:

--
[EnumeratingUserProfilesOnWin10client.txt](https://github.com/mitre/caldera/files/3011344/EnumeratingUserProfilesOnWin10client.txt)
--

**Comment by ArtificialErmine** [comment]
If there are any updates on this issue after upgrading to the most recent Caldera release, please feel free to re-open it, otherwise it will be closed due to inactivity.
