### ISSUE TITLE
Caldera startup fail due to Adversary

### ISSUE THREAD

**Issue by perra22** [mitre/adversary#32]
Hello, 
i'm trying to use Adversary plugin but when i do 

> `python3 server.py -E local`

i get this error

>  Traceback (most recent call last):
>   File "server.py", line 99, in <module>
>     plugin_modules = build_plugins(config['plugins'])
>   File "server.py", line 84, in build_plugins
>     modules.append(import_module('plugins.%s.hook' % plug))
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/perra/Desktop/stage/caldera/plugins/adversary/hook.py", line 3, in <module>
>     import plugins.adversary.app.config as config
>   File "/home/perra/Desktop/stage/caldera/plugins/adversary/app/config.py", line 6, in <module>
>     from plugins.adversary.app.database.dao import Dao
>   File "/home/perra/Desktop/stage/caldera/plugins/adversary/app/database/dao.py", line 1, in <module>
>     from plugins.adversary.app.database.mongo import Mongo
>   File "/home/perra/Desktop/stage/caldera/plugins/adversary/app/database/mongo.py", line 3, in <module>
>     from plugins.adversary.app.database.model import Model
>   File "/home/perra/Desktop/stage/caldera/plugins/adversary/app/database/model.py", line 1, in <module>
>     from plugins.adversary.app.utility.general import nested_get
>   File "/home/perra/Desktop/stage/caldera/plugins/adversary/app/utility/general.py", line 5, in <module>
>     import plugins.adversary.app.config as config
> AttributeError: module 'plugins.adversary.app' has no attribute 'config'

i've already installed mongo and all requirements. i've also attached my local.yml (.txt for GitHub supported file type).
Thank you!
[local.txt](https://github.com/mitre/adversary/files/3197178/local.txt)

**Comment by perra22** [comment]
Thanks for the reference @wisedier but the issue is still here :/
After trying to use your modified Adversary plugin (with the new requirements) without success
i've created the dir:

> adversary/app/config

with inside __init__.py and config.py for solve 

> AttributeError: module 'plugins.adversary.app' has no attribute 'config'

and now there is this issue:


> Enter help or go to https://127.0.0.1:8888 in a browser
> ...Created user: admin:admin
> Traceback (most recent call last):
>   File "server.py", line 123, in <module>
>     main(services=services, host=cfg['host'], port=cfg['port'], sockets=cfg['sockets'], users=cfg['users'])
>   File "server.py", line 78, in main
>     loop.run_until_complete(init(host, port, services, users))
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
>     return future.result()
>   File "server.py", line 62, in init
>     await attach_plugins(app, services)
>   File "server.py", line 42, in attach_plugins
>     await plugin(app, services)
>   File "/home/perra/Desktop/stage/caldera/plugins/adversary/hook.py", line 56, in initialize
>     config.initialize_settings(config_path='plugins/adversary/conf/config.ini', filestore_path=store)
> AttributeError: module 'plugins.adversary.app.config' has no attribute 'initialize_settings'
> 
> 

Thank you in advance!

**Comment by wisedier** [comment]
@perra22 Did you add `adversary` in `cadera/conf/local.yml`?
Here is my `local.yml`. Check it once.
```yml
---
host: 127.0.0.1
port: 8888
terminal_port: 8880
debug_level: DEBUG
planner: plugins.stockpile.app.sequential
plugins:
  - sandcat
  - gui
  - chain
  - adversary
users:
  admin: admin
```
`plugins/adversary/app/config.py` is what `server.py` tried to import. You do not need to create `config` directory.

**Comment by perra22** [comment]
@wisedier yes, i've already added `adversary` in `caldera/conf/local.yml`. If i remove it Caldera starts up,  so i think that the problem is in the plugin.

I've tried to create the dir `adversary/app/config` to solve 

> `AttributeError: module 'plugins.adversary.app' has no attribute 'config'` 

because `caldera/plugins/adversary/app/utility/general.py` fails to import `config.py` if i don't create the dir with the `__init__.py` to communicate to the python interpreter that is an importable package.

**Comment by perra22** [comment]
@wisedier i've solved using relative imports as you suggested in #36.
Thanks a lot!
