### ISSUE TITLE
libraries for clipspy are no longer supported in Ubuntu 18.04

### ISSUE THREAD

**Issue by wisedier** [mitre/adversary#37]
I checked that **clipspy** package is in use but it cannot be used in Ubuntu 18.04 because required libraries libclips and libclips-dev which are mentioned in [clipspy installation guide](https://pypi.org/project/clipspy/) had been deleted. You can check this fact in https://launchpad.net/ubuntu/bionic/amd64/libclips and https://launchpad.net/ubuntu/bionic/amd64/libclips-dev.
For this reason, other users may get the below error:
```
junsang@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
junsang@ubuntu:~$ sudo apt install libclips libclips-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libclips
E: Unable to locate package libclips-dev
```

**Comment by khyberspache** [comment]
Where are you seeing this dependency in adversary module?

**Comment by rayhernandez** [comment]
> Where are you seeing this dependency in adversary module?

https://github.com/mitre/adversary/blob/master/app/logic/clips_logic.py

**Comment by ghost** [comment]
@rayhernandez good eye; that clips is actual an internal package (from MITRE) that we haven't pushed out yet. we use the package as an alternative planning/logic library to pydatalog, which is the adversary mode plugin logic library. 

in the operation.py module, you'll see this code snippet that looks for clips on the path, and if not, it falls back to our normal pydata:
```
try:
    from submodules.clips.app.logic.clips_logic import CLIPSContext as LogicContext
except ImportError:
    logging.warning("Couldn't find clips module. Falling back to slower pyDatalog")
    from plugins.adversary.app.logic.pydatalog_logic import DatalogContext as LogicContext
```

**Comment by ArtificialErmine** [comment]
@wisedier as mentioned by privateducky, the clips package you were referring to isn't actually required, nor is it publicly available (mainly due to it being experimental and a bit unstable). Caldera should work, as is, without an issue without it. 

Closing the issue due to the initial concern being addressed, feel free to re-open or create a new issue if you do not believe this to be the case.
