### ISSUE TITLE
CraterMain7.exe

### ISSUE THREAD

**Issue by workandresearchgithub** [mitre/adversary#4]
Downloaded cratermain for Windows 7:
--
https://github.com/mitre/caldera-crater/releases/download/v0.1.0/CraterMain7.exe
--
When I try to run it as on Windows 7, while logged in as a domain administrator, in a cmd window with "run as administrator", I get this error message:
--
c:\temp\CraterMainWin7.exe is not a valid Win32 application. 
-- 

Any ideas?

**Comment by ArtificialErmine** [comment]
The most recent iteration of Caldera utilizes a new method/api for distributing caldera directly from the adversary mode plugin. The agent can also be found directly here now: https://github.com/mitre/adversary/blob/master/payloads/CraterMain.exe.
