### ISSUE TITLE
Unable to add several hosts to a network

### ISSUE THREAD

**Issue by p57p57** [mitre/adversary#44]
Hi,
i am unable to add several hosts to a network through the GUI;

I click on a "domain" which then select all the hosts int his domain.
I click then new, enter the name of the network then click save.
At this time only one host is selected and added to the network. It is then impossible to add a new host.

The workaround is to manually add it directly using mongoDB interface  which is efficient but not recommended i suppose.

**Comment by vzairaj** [comment]
While creating a new network, if you select one host it will show you all the hosts in the same domain allowing you to add more hosts from that same domain. Previously, that first host you selected was highlighted with a different color. However, now in the latest version that is not happening.
Anyways, if you ignore the highlighting issue and just click the rest of the hosts you want to add BEFORE saving your new network, those hosts would be added properly but again the highlight will not occur...

**Comment by ArtificialErmine** [comment]
It turns out that some minor changes to the project had unexpected impacts on certain things, the highlighting of hosts during network instantiation being one of them. I've created a patch that's currently waiting to be pulled in (https://github.com/mitre/adversary/pull/47), that should fix this issue by restoring the highlighting.

**Comment by ArtificialErmine** [comment]
@p57p57 @EnJohnGee If the issue still persists after updating to the most recent version of Caldera and its plugins, feel free to reopen this ticket or create a new one. Otherwise, it appears #47 fixed the root issue here.
