### ISSUE TITLE
render in FileSvc missing

### ISSUE THREAD

**Issue by wietze** [mitre/adversary#51]
In commit abdd44bb5ba3b56f911b866a9ff0b301ebf6dc0e, the `/file/render` route and related code was deleted without explaning why. The Adversary plugin relies on this route, [for instance](https://github.com/mitre/adversary/blob/master/static/js/operation.js#L797-L807) to display the PowerShell script to install the CAgent to new machines.

**Comment by ArtificialErmine** [comment]
If this issue still exists, feel free to reopen the ticket, otherwise, I believe #47 fixed this.
