### ISSUE TITLE
Rat crashed during execution of PowerView commands

### ISSUE THREAD

**Issue by josephbleroy** [mitre/adversary#6]
I'm running into an issue where the Rat crashes during the execution of PowerView commands:

```
"function": "execute",
        "parameters": {
          "command_line": "powershell -command -",
          "stdin": "[[powerview]] Get-DomainComputer"
        }
      },
      "error": "Rat crashed during execution"
    },
    "create_time": "2018-11-29T01:19:36.725Z",
    "status": "failed"
```

From the command line, I'm also noticing the following output:

```
WARNING: The rat started as a local user. In order to function properly, Caldera requires domain users. Please verify that the starting rat is operating under a Domain Account if full functionality is desired.
```

For reference, I'm running CALDERA under the following architecture:

- CALDERA Server: Ubuntu 16.04.5. LTS using Docker-CE + Docker Compose
- CALDERA Agents: Windows 7 SP1 Enterprise x64 

I've made sure to setup `docker-compose.yaml` to include the following advanced configuration:

```
args: “crater=https://github.com/mitre/caldera-crater/releases/download/v0.1.0/CraterMain7.exe”
```

I've essentially followed the documentation verbatim. I don't seem to have any issues when running tasks that involve native Windows commands. 

Any thoughts on what might be causing this issue? I'm happy to provide more information to help troubleshoot and improve this project's documentation.

Thanks!

**Comment by josephbleroy** [comment]
> Two things to quickly try would be to verify that the machine the rat was running on can contact the Domain Controller, and that the output of Get-DomainComputer (you can download the appropriate powershell script and run it locally to check this) looks reasonable (i.e. it doesn't throw an error).

Thank you for your reply. I've gone ahead and downloaded PowerSploit to try and test the Get-DomainComputer command, however, our endpoint software is blocking it from extracting. 

I'll see if I can find a workaround so that I can test if the command actually works. However, it seems quite possible that maybe our endpoint software is preventing CALDERA from executing `Get-DomainComputer` from the RAT on the target system.

Do you think this is possibly the issue?

**Comment by ArtificialErmine** [comment]
This appears to have been encountered while using an older variant of Caldera. If the issue persists when upgrading to the most recent version, feel free to re-open this issue, and we'll try to help debug the root cause and potential solutions further.
