### ISSUE TITLE
RAT starting as  local user instead of a Domain User

### ISSUE THREAD

**Issue by Manuuuux** [mitre/adversary#8]
Hello, first of all, thank you for this amazing project.

I have a problem that I can't solve. I'll explain what it is, when I start an operation the RAT always starts as a Local user instead of as a Domain User.
I don't understand why, since, I am logged in an account that belongs to the domain.
Any idea?

Here is the Log:

DEBUG:app.operation.operation:starting operation
INFO:app.operation.operation:Writing commander to: 'C:\commander.exe'
INFO:app.operation.operation:Bootstrapping rat with SYSTEM account
INFO:app.operation.operation:Rat callback: 5bc7516988447457f8d88ea3
**WARNING: The rat started as a local user. In order to function properly, Caldera requires domain users. Please verify that the starting rat is operating under a Domain Account if full functionality is desired.**

**Comment by cl-mitre** [comment]
That starts clearing things up. 

1.  The N?ever! issue is related to the current version of caldera not supporting non-ascii characters. An internal version provides this support, and we hope to release it soon, but for now, you may want to keep this limit in mind.
2.   The domain admin's credentials need to be obtain for this to work, so the problem you are seeing makes sense. Two things to check: 1) Have you verified that you turned credential caching on within the environment? (check the documentation for information on how to do this if you don't know), and 2) Have you made sure that the domain administrator account has recently logged into the machine that caldera is starting on?

**Comment by Manuuuux** [comment]
Yeah, I mean, I've created my own "Charlie" by removing the steps ( get_local_profiles and hku_runkey_persist), and adding others, however CALDERA is not able to do any of the Steps I'm having problems with.

**Comment by ArtificialErmine** [comment]
This issue was created when utilizing an older version of Caldera. If the issue still exists after upgrading to the most recent version, feel free to re-open this issue or create a new one, and we can try to debug the planner's activity further. In the mean time, this issue is being closed due to inactivity.
